### ISSUE TITLE
ctrl-c exitwith no fps in silent mode causes core dump

### ISSUE THREAD

**Issue by SimLeek** [SimLeek/displayarray#42]
```
^CTraceback (most recent call last):
  File "t.py", line 12, in <module>
    for up in display(0, size=(1, 1), silent=True ):
  File "/home/okwokk/.local/lib/python3.7/site-packages/displayarray/window/subscriber_windows.py", line 62, in __iter__
    self.update()
  File "/home/okwokk/.local/lib/python3.7/site-packages/displayarray/window/subscriber_windows.py", line 201, in update
    key = self.handle_keys(cv2.waitKey(1))
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
terminate called without an active exception
Aborted (core dumped)
```

**Comment by okawo80085** [comment]
here is the code responsible for the core dump on ctrl-c
```python
from displayarray import display
import time

t0 = t1 = time.time()
for up in display(0, size=(1, 1), silent=True ):
    if up:
        t1 = time.time()
        print(f'{(t1 - t0)}/{1/60}s')
        t0 = t1
```
